stages:
  - test
  - gittag
  - publish

.before_npm: &before_npm_def
  before_script:
    - npm install -g yarn --force

test:
  stage: test
  image: node:14-alpine
  <<: *before_npm_def
  script:
    - yarn install
    - npm test a

gittag:
  stage: gittag
  image: gitlab-registry.cern.ch/authzsvc/tools/gitlab-python-tools
  script:
    # Make sure the latest version in package.json is higher than the latest one in gitlab
    - new_tag=$(cat package.json | jq -r '.version')
    - gitlab-tag-latest -t $GITLAB_TOKEN $CI_PROJECT_NAME $new_tag
  only:
    - master

publish:
  stage: publish
  image: node:14-alpine
  <<: *before_npm_def
  script:
    - apk add git
    - yarn install
    - printf "\n_auth=$NEXUS_NPM_AUTH\n" >> .npmrc
    - yarn publish --non-interactive --new-version $CI_COMMIT_TAG --no-git-tag-version
  only:
    - tags
